# Site settings
title: Alannah
header-img: img/home-bg.jpg
email: alannahyoho@gmail.com
description: "A blog all about a day in the life of a professional cookie maker"
baseurl: ""
url: "alblog.ddns.net"
twitter_username: alannahyoho
github_username: alannahyoho
facebook_username: alannahyoho

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
