# Site settings
title: Alannah's Blog
header-img: img/home-bg.jpg
email: sebamor12@gmail.com
description: "Alannah's Blog"
baseurl: "sebamor.github.io/alBlog"
url: "sebamor.github.io/alBlog"
twitter_username: Sebamor
github_username:  Sebamor
facebook_username:  Alannah Yoho

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
