# Site settings
title: Alannah
header-img: img/home-bg.jpg
email: sebamor12@gmail.com
description: "A blog all about a day in the life of a professional cookie maker"
baseurl: ""
url: "alblog.ddns.net"
twitter_username: Alannah's Classic Homemade Cookies
github_username: Sebamor
facebook_username: Alannah Cookies

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
